services:
  - type: web
    name: press-release-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: press-release-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: press-release-app-db
    databaseName: press_release_app_production
    user: press_release_app 